name: Deploy to Production
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: self-hosted
    timeout-minutes: 30
    steps:
      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            bash /production/deploy-backend.sh 

